version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0a:f1:27:85:56:44:07:44:50:60:40:8f:1f:73:b5:30"
      - run:
          name: Github config
          command: |
            git config user.email "matteo.vannucchi11@gmail.com"
            git config user.name "matteo00111"
      - run:
          name: Deploy to server
          command: | 
            ssh-keyscan -H donpasquale.cs.unibo.it >> ~/.ssh/known_hosts

            scp -r public/models/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/backend/
            scp -r public/routers/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/backend/
            scp -r public/lib/ matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/public/backend/
            

            scp index.js matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/
            scp package.json matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/
            scp package-lock.json matteo.vannucchi@donpasquale.cs.unibo.it:/home/web/site202120/html/  
      - run:
          name: Install npm packages
          command: |
            ssh matteo.vannucchi@donpasquale.cs.unibo.it "bash --login -c 'cd /home/web/site202120/html && npm install --only=production' "
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
