@router-uri = http://localhost:8000/clients

GET {{router-uri}}

###

POST {{router-uri}}
content-type: application/json

{
    "firstName": "John",
    "lastName": "Smith"
}

###

DELETE {{router-uri}}/615057175ccbd1e31f38f5f7