@id = 615371748968b8c7a8024010

GET http://localhost:8000/Products

###

GET http://localhost:8000/Products/{{id}}

###

POST http://localhost:8000/Products
Content-Type: application/json

{
    "title": "Macchina X",
    "description": "Una bellissima automobile"
}

###

DELETE http://localhost:8000/Products/{{id}}

###

PATCH http://localhost:8000/Products/{{id}}
Content-Type: application/json

{
    "title": "Macchina X",
    "description": "Una automobile"
}